version: "3"

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npx workbox-cli generateSW workbox-config.js && npm start"
  backend:
    build: ./server
    ports:
      - "3001:3001"
    restart: always
    command: sh -c "npm start"
